# The west manifest file (west.yml) for the NXP ZSDK
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.
#
#     [manifest]
#     path = zsdk
#
manifest:
  version: "1.2"

  # "remotes" is a list of locations where git repositories are cloned
  # and fetched from.
  remotes:
    - name: nxp
      url-base: https://github.com/NXP
    - name: nxp-zsdk
      url-base: https://github.com/nxp-zephyr
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  # If not otherwise specified, the projects below should be obtained
  # from the zsdk remote.
  defaults:
    remote: nxp-zsdk

  group-filter: [+optional, -bifrost]

  # "projects" is a list of git repositories to populate NXP Zephyr downstream
  # workspace.
  projects:

    - name: zephyr
      repo-path: nxp-zephyr
      revision: 71a0f5d33d8b557b6950ba2e54cc7d512cc1d53f
      import:
        #
        # ZSDK imports the contents of nxp-zephyr/west.yml at the above
        # revision. Only the projects explicitly named in the
        # following allowlist are imported.
        #
        # If there is an override of one of the Zephyr modules,
        # remove it from the name-allowlist and add the project
        # explicitly below the list.
        #
        name-allowlist:
          - TraceRecorderSource
          - canopennode
          - chre
          - cmsis
          - cmsis-dsp
          - cmsis-nn
          - cmsis_6
          - edtt
          - fatfs
          - hal_nxp
          - hal_st
          - hal_xtensa
          - liblc3
          - libsbc
          - libmetal
          - littlefs
          - loramac-node
          - lvgl
          - lz4
          - mcuboot
          - mipi-sys-t
          - net-tools
          - open-amp
          - picolibc
          - segger
          - tinycrypt
          - uoscore-uedhoc
          - zcbor
          - zscilib
          - openthread

    # For internal NXP development support
    - name: bifrost
      west-commands: scripts/west_commands.yml
      repo-path: bifrost
      revision: bca5f40f6aa7eb55957dbbd28a4e988f23336072
      groups:
        - bifrost

    #
    # NXP based overrides of Zephyr modules and additional
    # added modules
    #
    - name: hal_nxp
      revision: 1fa027e67ce6f5fa56004edf3a1b3985e5c57b59
      path: modules/hal/nxp
      groups:
        - hal
    - name: els_pkc
      remote: nxp
      repo-path: els_pkc
      revision: 71d4a89c03fb32e618ee02c0cd54b3fc92736c96
      path: modules/crypto/els_pkc
      groups:
        - crypto
    - name: psa_crypto_driver
      remote: nxp
      repo-path: psa_crypto_driver
      revision: 1a93893f986db38cf2c8910f6138b634f0437a48
      path: modules/crypto/psa_crypto_driver
      groups:
        - crypto
    - name: mbedtls
      remote: nxp
      repo-path: nxp_mbedtls
      revision: 73423cfa8d939941b08321af042762c718fc78bf
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: trusted-firmware-m
      remote: nxp
      repo-path: nxp_tf-m
      revision: 17a27cc0e4e709e561ab8e95260f8bec68211398
      path: modules/tee/tf-m/trusted-firmware-m
      groups:
        - tee
    - name: psa-arch-tests
      remote: nxp
      repo-path: nxp_psa_arch_test
      revision: 32784fe0367394a6e70dfe1771e0301cb4ab76f3
      path: modules/tee/tf-m/psa-arch-tests
      groups:
        - tee
    - name: tf-m-tests
      revision: a286347e6a5dd37a9a5e960450ffc0260d63fb27
      path: modules/tee/tf-m/tf-m-tests
      remote: zephyrproject
      groups:
        - tee
    - name: hostap
      repo-path: hostap
      revision: de484a92e23576b92b0d808b34fceacb114dff01
      path: modules/lib/hostap
    - name: wifi_nxp
      remote: nxp
      repo-path: wifi_nxp
      revision: b2058399fc2eb1ea742534922448fc2e3d4b8efa
      path: modules/hal/nxp/mcux/middleware/wifi_nxp
    - name: wifi_nb_fw
      remote: nxp
      repo-path: wifi_nb_fw
      revision: e7e832808bed328bf6cbbdb963780413e3406322
      path: modules/hal/nxp/zephyr/blobs/
    - name: nxp_iot_agent
      remote: nxp
      repo-path: el2go-agent
      revision: 3eba50dbec2ba51b9d099236c580caa005df6fbe
      path: modules/lib/nxp_iot_agent

    # Add any additional third-party repositories.

  self:
    path: zsdk
    # Configure west extensions.
    #west-commands: scripts/west-commands.yml
