# Config stack size
CONFIG_MAIN_STACK_SIZE=8192

# Kernel options
CONFIG_INIT_STACKS=y

# Mbedtls configuration
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_MBEDTLS_INIT=n

#enable supported algos
CONFIG_PSA_WANT_ALG_CBC_PKCS7=y
CONFIG_PSA_WANT_ALG_CBC_NO_PADDING=y
CONFIG_PSA_WANT_ALG_CBC_PKCS7=y
CONFIG_PSA_WANT_ALG_CTR=y
CONFIG_PSA_WANT_KEY_TYPE_AES=y
CONFIG_PSA_WANT_ALG_SHA_256=y


# enable psa crypto usage
CONFIG_MBEDTLS_PSA_CRYPTO_C=y
# enable entropy
CONFIG_MBEDTLS_ENTROPY_C=y

# Disable zephyr_entropy implementation,
# we use our own mbedtls_hardware_poll() implementation in MbedTLS
CONFIG_MBEDTLS_PSA_CRYPTO_EXTERNAL_RNG=n
